---
helpers:
  browser-sync: npm run server
exclude:
- '*.pl'
- '*.csv'
- '*.sh'
- /node_modules
- /package.json
- /package-lock.json
- /COVID-19
- /LocaleData
linguas: [en, de]
defaults:
- files:
  - /en
  values:
    lingua: en 
- files:
  - /de
  values:
    lingua: de
po:
  textdomain: corona-numbers
  msgid-bugs-address: Guido Flohr <guido.flohr@cantanea.com>
  copyright-holder: cantanea EOOD <http://www.cantanea.com/>
  reload: 1

