---
helpers:
  browser-sync: npm run server
exclude:
- '*.pl'
- '*.csv'
- '*.sh'
- /node_modules
- /package.json
- /package-lock.json
- /COVID-19
linguas: [en, de]
defaults:
- files:
  - /en
  values:
    lingua: en 
- files:
  - /de
  values:
    lingua: de
